#!/bin/bash

if [ $# -ne 1 ]; then
    echo ": Specify name of file you want to extract with first argument."
    exit 1
fi

file_name=$1

if [ -e "$file_name" ]; then
    tar -xvzf "$file_name"
else
    echo "File '$file_name' does not exist."
fi
